steps:
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/vpc_subnets
    args:
      - '-c'
      - |
        terraform init
    id: terraform init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/vpc_subnets
    args:
      - '-c'
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/vpc_subnets
    args:
      - '-c'
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/vpc_subnets
    args:
      - '-c'
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/vpc_subnets
    args:
      - '-c'
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh
steps:
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/nat_gateway
    args:
      - '-c'
      - |
        terraform init
    id: terraform init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/nat_gateway
    args:
      - '-c'
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/nat_gateway
    args:
      - '-c'
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/nat_gateway
    args:
      - '-c'
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/nat_gateway
    args:
      - '-c'
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh
steps:
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/firewall_rules
    args:
      - '-c'
      - |
        terraform init
    id: terraform init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/firewall_rules
    args:
      - '-c'
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/firewall_rules
    args:
      - '-c'
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/firewall_rules
    args:
      - '-c'
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/global/networking/firewall_rules
    args:
      - '-c'
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh   
logsBucket: 'gs://accelerators-us-central1'
options:
  logging: GCS_ONLY         
