steps:
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/regions/us-central1/gke_cluster
    args:
      - '-c'
      - |
        terraform init
    id: terraform init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/regions/us-central1/gke_cluster
    args:
      - '-c'
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/regions/us-central1/gke_cluster
    args:
      - '-c'
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/regions/us-central1/gke_cluster
    args:
      - '-c'
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.7'
    dir: terraform/env/main/regions/us-central1/gke_cluster
    args:
      - '-c'
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh  
timeout: 2100s     
logsBucket: 'gs://accelerators-us-central1'
options:
  logging: GCS_ONLY         
